kernels:
  open_kernel: 20
  close_kernel: 13

checkerboard_dimensions:
  x: 9
  y: 6

paths:
  fish: "fishpics/NewFish"
  checkerboard_calibration: "fishpics/CheckerBoards"
  fish_histogram_test: "fishpics/Test11"

clahe:
  clipLimit: 2
  tileGridSize: !!python/tuple [20, 20]